### ISSUE TITLE
关于多进程实时生成视频的问题

### ISSUE THREAD

**Issue by mrlihellohorld** [SkyFlap/Digital-Life-DL-B#1]
您好，我看您在b站公开的视频提到生成的回答结果是生成一部分后就生成音频然后拿去生成视频，这样可以节省时间从而达到实时处理。但是我看您的代码中，好像并没有做这样的处理，依然还是生成整个音频之后，再去做的视频驱动。而且So-VITS_run和wav2lip_run的调用是用的os.system，这是阻塞的。

**Comment by SkyFlap** [comment]
感谢您的提问，目前开源出来的是最初版本的代码，并行处理是在后续版本中增加的，目前这部分代码还没有进行开源。事实上虽然目前进行了并行处理但也并不完全是流式的，我对于流媒体部分没有任何知识和经验，所以对于音频和视频的流式处理并不清楚。
