### ISSUE TITLE
低配电脑的救星 - JittorLLMs 的支持

### ISSUE THREAD

**Issue by PlayMcBKuwu** [SkyFlap/Digital-Life-DL-B#2]
https://github.com/Jittor/JittorLLMs/
希望可以用这个替代原生 ChatGLM
~~顺带说下，原生 ChatGLM 出 2 代了，可以考虑更新（雾）~~

**Comment by SkyFlap** [comment]
感谢您的提问，是的我知道计图框架，但是目前这个框架的支持性并不是非常可靠（依据我在4月份的测试，4月份的版本中仍然会有许多的BUG）
GLM2的代码实际上是一样的，可以自己更新一下checkpoints就可以（理论上）（而且我最近使用GLM2的过程中并没有实际感受到使用体验上的提升），如果你在更改代码之后出现了bug欢迎继续提问。
