### ISSUE TITLE
请问DL-C/DL-D有计划开源吗？

### ISSUE THREAD

**Issue by LvHuaiSheng** [SkyFlap/Digital-Life-DL-B#3]
请问DL-C/DL-D有计划开源吗？

**Comment by SkyFlap** [comment]
事实上后续由于种种原因我们并没有把项目推进下去，这个已经被搁置很久了，非常抱歉。不过如果你愿意并且感兴趣可以添加微信LingMu_sea。请备注您的Github用户名，我们可以进行一些交流。
